--- 
- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest
    update_cache: yes
  tags:
    - Install

- name: Desabilitando o SELinux
  selinux:
    state: disabled

- name: Baixando epel-release
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
